describe('Contact Form Tests', () => {
  beforeEach(() => {
    cy.visit('/contact');
    cy.intercept('POST', (Cypress.env('PRIMARY_SITE_URL') + '/actions/formie/submissions/submit')).as('submission');
  });

  it('Checks that the General Contact form is working', () => {
    cy.findByRole('radio', {name: /General/i}).then(($radio) => {
      cy.wrap($radio).should('be.checked');
    });

    cy.findByRole('textbox', {name: /Name/i}).type(Cypress.env('FIRSTNAME'));
    cy.findByRole('textbox', {name: /Email/i}).type(Cypress.env('TEST_EMAIL'));
    cy.findByRole('textbox', {name: /Message/i}).type('This is a general test message generated by Cypress.');
    cy.findByRole('button', {name: /Send/i}).click();
    cy.wait('@submission');
    cy.findByText(/Thank you/i).should('exist');
  });

  it('Checks that the Project Inquiry form is working', () => {
    cy.findByRole('radio', {name: /Project inquiry/i}).click({force: true}).then(($radio) => {
      cy.wrap($radio).should('be.checked');
    });

    cy.findByRole('textbox', {name: /Name/i}).type(Cypress.env('FIRSTNAME'));
    cy.findByRole('textbox', {name: /Email/i}).type(Cypress.env('TEST_EMAIL'));
    cy.findByRole('radio', {name: /Custom plugin/i}).click({force: true});
    cy.findByRole('textbox', {name: /Message/i}).type('This is a product inquiry test message generated by Cypress.');
    cy.findByRole('button', {name: /Send/i}).click();
    cy.wait('@submission');
    cy.findByText(/Thank you/i).should('exist');
  });

  it('Checks that the Support form is working', () => {
    cy.findByRole('radio', {name: /Support/i}).click({force: true}).then(($radio) => {
      cy.wrap($radio).should('be.checked');
    });

    cy.findByRole('textbox', {name: /Name/i}).type(Cypress.env('FIRSTNAME'));
    cy.findByRole('textbox', {name: /Email/i}).type(Cypress.env('TEST_EMAIL'));
    cy.findByRole('textbox', {name: /Message/i}).type('This is a support test message generated by Cypress.');
    cy.findByRole('button', {name: /Send/i}).click();
    cy.wait('@submission');
    cy.findByText(/Thank you/i).should('exist');
  });
});